import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "blog app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={`${geistSans.variable} ${geistMono.variable} antialiased home-page`}
       
      >
        {children}
      <header>
      <h1>Logo</h1>
      <nav>
        <a href = "./">Home</a>
        <a href = "./about">About</a>
        <button >login</button>
        <button >sign up</button>
      </nav>
      </header>
      </body>
    </html>
  );
}
